### ISSUE TITLE
Implement Interfaces

### ISSUE THREAD

**Issue by vbjay** [ZdsAlpha/Fraction#1]
Make fraction inherit from https://msdn.microsoft.com/en-us/library/system.valuetype(v=vs.110).aspx ValueType.

Get rid of shadows and override ToString.

**Comment by ZdsAlpha** [comment]
But it is structure not a class.

**Comment by vbjay** [comment]
Ok.  In that case you might want to look at implementing 
IComparable, IFormattable, IConvertible
        , IComparable(of Fraction), IEquatable(of Fraction)

**Comment by ZdsAlpha** [comment]
Some conversions are not possible e.g conversion to char or DateTime.
Also GetTypeCode cannot be implemented because it is none of pre-defined types.

**Comment by ZdsAlpha** [comment]
Implemented over IComparable, IComparable(Of Fraction), IEquatable(Of Fraction).
